language: node_js

node_js:
  - stable

services:
  - mysql

env:
  - NODE_ENV=test

before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS testDB;'
  - mysql -e 'USE testDB;CREATE TABLE IF NOT EXISTS Tests (id INT NOT NULL AUTO_INCREMENT PRIMARY KEY, title VARCHAR(250), createdAt DATETIME, updatedAt DATETIME)';
  - mysql -e 'USE testDB;CREATE TABLE IF NOT EXISTS Easies (id INT NOT NULL AUTO_INCREMENT PRIMARY KEY, selfText TEXT, selfText_html TEXT, url VARCHAR(255), title VARCHAR(255), difficulty VARCHAR(255), createdAt DATETIME, updatedAt DATETIME)';
  - mysql -e 'USE testDB;CREATE TABLE IF NOT EXISTS Hards (id INT NOT NULL AUTO_INCREMENT PRIMARY KEY, selfText TEXT, selfText_html TEXT, url VARCHAR(255), title VARCHAR(255), difficulty VARCHAR(255), createdAt DATETIME, updatedAt DATETIME)';
  - mysql -e 'USE testDB;CREATE TABLE IF NOT EXISTS Intermediates (id INT NOT NULL AUTO_INCREMENT PRIMARY KEY, selfText TEXT, selfText_html TEXT, url VARCHAR(255), title VARCHAR(255), difficulty VARCHAR(255), createdAt DATETIME, updatedAt DATETIME)';
  - mysql -e 'USE testDB;CREATE TABLE IF NOT EXISTS Quotes (id INT NOT NULL AUTO_INCREMENT PRIMARY KEY, text TEXT, author VARCHAR(255), createdAt DATETIME, updatedAt DATETIME)';
  