language: node_js

node_js:
  - stable

services:
  - mysql

env:
  - NODE_ENV=test

before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS testDB;'
  - mysql -e 'CREATE TABLE TEST id INT NOT NULL AUTO_INCREMEMNT PRIMARY KEY, title VARCHAR;'